CustomAuthenticationMVC/CustomAuthenticationMVC/Controllers/QuizController.cs
using CustomAuthenticationMVC.DataAccess;
using CustomAuthenticationMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using PagedList.Mvc;
namespace CustomAuthenticationMVC.Controllers
{
    public partial class QuizController : Controller
    {
        // GET: Quiz
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public ActionResult AddQuestion()
        {
            var question = new Question();
            if(TempData["tags"] != null)
            question.QuestionTags = TempData["tags"].ToString();
            using (AuthenticationDB dbContext = new AuthenticationDB())
            {
                //string query = "select distinct questionSubject FROM questions";
                //var subjects = dbContext.Database.SqlQuery<string>(query).ToList();
            }
            return View(question);
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditQuestion(int questionId)
        {
            using (AuthenticationDB dbContext = new AuthenticationDB())
            {
                var question = dbContext.Questions.Find(questionId);
                TempData.Keep();
                return View(question);
            }
        }

        [Authorize]
        [HttpGet]
        public JsonResult GetTopics(string subject)
        {
            //var topics = new List<string>();
            //using (AuthenticationDB dbContext = new AuthenticationDB())
            //{
            //    string query = "select distinct questionTopic FROM questions WHERE questionSubject = @p0";
            //    topics = dbContext.Database.SqlQuery<string>(query, subject).ToList();
            //}
            return Json(null, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult AddTag(string tagName)
        {
            if (ModelState.IsValid)
            {
                using (AuthenticationDB dbContext = new AuthenticationDB())
                {
                    var tag = new Tag();
                    tag.TagName = tagName;
                    dbContext.Tags.Add(tag);
                    dbContext.SaveChanges();
                }
                return Json("Tag Added", JsonRequestBehavior.AllowGet);
            }
            return Json("Tag Adding Failed", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetTags()
        {
            
            var tags = new List<Tag>();
            using (AuthenticationDB dbContext = new AuthenticationDB())
            {
                tags = dbContext.Tags.ToList();
            }
            return Json(tags, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetAllQuestions(string sortOrder, string sortParam, string currentFilter, string searchString, string userString, string userFilter, string completedString, string completedFilter,  int? page)
        {
            TempData["CurrentSort"] = sortOrder;
            TempData["NameSortParm"] = String.IsNullOrEmpty(sortParam) ? "date_desc" : sortParam;
            TempData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            TempData["CurrentFilter"] = searchString;

            if (userString != null)
            {
                page = 1;
            }
            else
            {
                userString = userFilter;
            }
            TempData["UserFilter"] = userString;


            if (completedString != null)
            {
                page = 1;
            }
            else
            {
                completedString = completedFilter;
            }
            TempData["CompletedFilter"] = completedString;

            var questions = new List<Question>().AsQueryable();
            using (AuthenticationDB dbContext = new AuthenticationDB())
            {
                questions = dbContext.Questions;
                if (!String.IsNullOrEmpty(searchString))
                {
                    questions = questions.Where(s => s.QuestionTags.Contains(searchString)
                                           || s.QuestionText.Contains(searchString));
                }
                if (!String.IsNullOrEmpty(userString))
                {
                    questions = questions.Where(s => s.AddedBy.Equals(userString)
                                           || s.AddedBy.Contains(userString));
                }
                if (!String.IsNullOrEmpty(completedString))
                {
                    questions = questions.Where(s => s.IsReady.Equals(true));
                }
                switch (sortParam)
                {
                    case "tags":
                        questions = questions.OrderBy(q => q.QuestionTags);
                        break;
                    case "question":
                        questions = questions.OrderBy(q => q.QuestionText);
                        break;
                    //case "Date":
                    //    questions = questions.OrderBy(s => s.EnrollmentDate);
                    //    break;
                    case "date_desc":
                        questions = questions.OrderByDescending(q => q.CreatedOn);
                        break;
                    default:
                        questions = questions.OrderByDescending(q => q.CreatedOn);
                        break;
                }
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                TempData["pageNumber"] = pageNumber;
                return View(questions.ToPagedList(pageNumber, pageSize));
            }
        }

        [HttpPost]
        public ActionResult EditQuestion(QuestionView questionView, bool continueEditing)
        {
            if (ModelState.IsValid)
            {
                using (AuthenticationDB dbContext = new AuthenticationDB())
                {
                    var question = dbContext.Questions.First(q => q.QuestionId == questionView.QuestionId);
                    question.QuestionTags = questionView.QuestionTags;
                    question.QuestionText = questionView.QuestionText;
                    question.QuestionDescription = questionView.QuestionDescription;
                    question.QuestionPicPath = questionView.QuestionPicPath;
                    question.RightAnswer = questionView.RightAnswer;
                    question.OptionA = questionView.OptionA;
                    question.OptionB = questionView.OptionB;
                    question.OptionC = questionView.OptionC;
                    question.OptionD = questionView.OptionD;
                    question.OptionE = questionView.OptionE;
                    question.OptionF = questionView.OptionF;
                    question.IsReady = (question.OptionA != null && question.OptionA != null && question.RightAnswer != null) ? true : false;
                    question.AddedBy = User.Identity.Name;
                    question.EditedOn = DateTime.Now;
                    dbContext.SaveChanges();
                    if (continueEditing)
                    {
                        question = dbContext.Questions.First(q => q.QuestionTags == questionView.QuestionTags && q.IsReady == false);
                        return RedirectToAction("EditQuestion", new { questionId = question.QuestionId });
                    }
                }
                
                return RedirectToAction("GetAllQuestions", new { page = TempData["pageNumber"], sortParam = TempData["NameSortParm"], sortOrder = TempData["CurrentSort"], currentFilter = TempData["CurrentFilter"], userFilter = TempData["UserFilter"], completedFilter = TempData["CompletedFilter"] });
            }
            ModelState.AddModelError("", "Something Wrong");
            TempData["tags"] = questionView.QuestionTags;
            return View();
        }

        [HttpPost]
        public ActionResult AddQuestion(QuestionView questionView)
        {
            if (ModelState.IsValid)
            {
                using (AuthenticationDB dbContext = new AuthenticationDB())
                {
                    var question = new Question();
                    question.QuestionTags = questionView.QuestionTags;
                    question.QuestionText = questionView.QuestionText;
                    question.QuestionDescription = questionView.QuestionDescription;
                    question.QuestionPicPath = questionView.QuestionPicPath;
                    question.RightAnswer = questionView.RightAnswer;
                    question.OptionA = questionView.OptionA;
                    question.OptionB = questionView.OptionB;
                    question.OptionC = questionView.OptionC;
                    question.OptionD = questionView.OptionD;
                    question.OptionE = questionView.OptionE;
                    question.OptionF = questionView.OptionF;
                    question.IsReady = (question.OptionA != null && question.OptionA != null && question.RightAnswer != null) ? true : false;
                    question.AddedBy = User.Identity.Name;
                    question.CreatedOn = DateTime.Now;
                    dbContext.Questions.Add(question);
                    dbContext.SaveChanges();
                }
                TempData["tags"] = questionView.QuestionTags; ;
                return RedirectToAction("AddQuestion");
            }
            ModelState.AddModelError("", "Something Wrong");
            TempData["tags"] = questionView.QuestionTags;
            return View();
        }

        [HttpGet]
        public ActionResult DeleteQuestion(int questionId)
        {

CustomAuthenticationMVC/CustomAuthenticationMVC/Views/Quiz/AddQuestion.cshtml
@model CustomAuthenticationMVC.DataAccess.Question

@{
    ViewBag.Title = "AddQuestion";
    Layout = "~/Views/Shared/_LayoutEmpty.cshtml";
}

@section styles {

}

<div class="container body-content">


    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "signupform" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">


            <div class="form-group">
                <div class="col-md-12">
                    @Html.TextAreaFor(model => model.QuestionText, htmlAttributes: new { @class = "form-control", @rows = "3", @id = "questionbx", @placeholder = "Question", @style = "", @required = "required", @tabindex = "1" })
                    @Html.ValidationMessageFor(model => model.QuestionText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    @Html.TextAreaFor(model => model.RightAnswer, htmlAttributes: new { @class = "form-control", @placeholder = "Answer", @id = "answerbx", @rows = "4", @style = "", @tabindex = "2" })
                    @Html.ValidationMessageFor(model => model.RightAnswer, "", new { @class = "text-danger" })
                </div>
            </div>











            <div class="row">


                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.OptionA, htmlAttributes: new { @class = "form-control", @placeholder = "Option A", @tabindex = "3", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.OptionA, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.OptionB, htmlAttributes: new { @class = "form-control", @placeholder = "Option B", @tabindex = "4", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.OptionB, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.OptionC, htmlAttributes: new { @class = "form-control", @placeholder = "Option C", @tabindex = "5", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.OptionC, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.OptionD, htmlAttributes: new { @class = "form-control", @placeholder = "Option D", @tabindex = "6", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.OptionD, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.OptionE, htmlAttributes: new { @class = "form-control", @placeholder = "Option E", @tabindex = "7", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.OptionE, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.OptionF, htmlAttributes: new { @class = "form-control", @placeholder = "Option F", @tabindex = "8", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.OptionF, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.QuestionDescription, htmlAttributes: new { @class = "form-control", @placeholder = "Description", @tabindex = "9", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.QuestionDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.QuestionPicPath, htmlAttributes: new { @class = "form-control", @placeholder = "Picture Path", @tabindex = "10", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.QuestionPicPath, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <div class="col-md-12">
                        @Html.TextAreaFor(model => model.QuestionTags, htmlAttributes: new { @class = "form-control", @id = "target", @placeholder = "Tags", @required = "required", @rows = "1" })
                        @Html.ValidationMessageFor(model => model.QuestionTags, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <div class="dropdown-mul-1 col-md-12">
                        <select style="display:none" name="" class="form-control" id="" multiple placeholder="Select"> </select>
                    </div>
                    @Html.ValidationMessageFor(model => model.QuestionTags, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-12">
                    <input type="submit" value="Add Question" style="min-width:100%;" class="btn btn-primary" id="submitButton" onclick="return submitForm()" />
                </div>
            </div>


        </div>
    }
    @*<div class="jquery-script-clear"></div>*@
</div>


@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@



@section scripts {
    <script>
            $('#questionbx').focus();
            function submitForm(){
                if ($('#questionbx').val() == "") {
                    $("#questionbx").css("border-color", "red");
                    return false;
                }
                if ($('#target').val() == "") {
                    $("#target").css("border-color", "red");
                    return false;
                }
                document.getElementById('signupform').submit();
            }
            $(document).keydown(function (e) {
                if (e.which === 83 && e.ctrlKey) {
                    e.preventDefault();
                    //$('#submitButton').click();
                    submitForm();
                }
            });
            $("#questionbx").focus(function () {
                $("#questionbx").css("border-color", "#ccc");
            });
            $("#target").focus(function () {
                $("#target").css("border-color", "#ccc");
            });

            var dropDownData = [];
            var dropDownValue = [];
            function addTag() {
                var tagName = $('#tagSearch').val();
                var tagId = (dropDownData[dropDownData.length - 1].id + 1).toString();
                dropDownData.push({ name: tagName, id: tagId.toString() });
                $('.dropdown-mul-1').data('dropdown').update(dropDownData, true);
                //$('.dropdown-mul-1').data('dropdown').config.data.push({ name: tagName, id: tagId });
                $('.dropdown-mul-1').data('dropdown').choose(tagId, true);
                var url = "/Quiz/AddTag?tagName=" + $('#tagSearch').val();
                $.get(url, function (data) {
                    //$(".result").html(data);
                    //dropDown.config.data.push({ name: tagName, id: '33', selected: true });
                });
                $('#tagSearch').val("");

            }

            function getTags() {
                var url = "/Quiz/GetTags";
                $.get(url, function (data) {
                    dropDownData = data.map(function (item) {
                        var newObject = { name: item.TagName, id: item.TagId }
                        return newObject;
                    });
                    $('.dropdown-mul-1').data('dropdown').update(dropDownData, true);
                });
            }
            @if (@ViewBag.tags != null)
            {
                <Text>
                $('#target').val(ViewBag.tags.toString());
                </Text>
            }

            $(document).ready(function () {
                $('.dropdown-mul-1').dropdown({
                    data: [],
                    limitCount: 40,
                    multipleMode: 'label',
                    choice: function () {
                        //console.log(arguments, this);
                        if (arguments && arguments[1] == null && arguments[0].target.parentElement.textContent) {
                            //alert(arguments[0].target.parentElement.textContent + " removed");
                            dropDownValue.pop(arguments[0].target.parentElement.textContent);
                            $('#target').val(dropDownValue.join(','));
                        }
                        if (arguments && arguments[1].selected == true) {
                            //alert(arguments[1].name + " selected");
                            dropDownValue.push(arguments[1].name);
                            $('#target').val(dropDownValue.join(','));
                            //var value = $('#target').val();
                            //$('#target').val(value + ',' + arguments[1].name);
                        }
                        if (arguments && arguments[1].selected == false) {
                            //alert(arguments[1].name + " removed");
                            dropDownValue.pop(arguments[1].name);
                            $('#target').val(dropDownValue.join(','));
                        }
                    //$('.dropdown-mul-1').data('dropdown').update(dropDownData, true);
                    },
                    init: function () {
                        getTags();
                    },
                    input: '<input type="text" maxLength="500" style="height:23px;" id="tagSearch" placeholder="Select Tags...">',
                    searchNoData: '<button class="btn btn-default col-md-12 col-sm-12 col-lg-12" style="color:blue" onclick="addTag()">Add</button>',
                });

            });
        $('textarea').autoResize();
        $(function () {
            $('textarea').each(function () {
                $(this).height($(this).prop('scrollHeight')-12);
            });
        });
    </script>
}

CustomAuthenticationMVC/CustomAuthenticationMVC/Views/Quiz/DisplayQuiz.cshtml
@model CustomAuthenticationMVC.DataAccess.Question

@{
    ViewBag.Title = "AddQuestion";
    Layout = "~/Views/Shared/_LayoutEmpty.cshtml";
}

@section styles {

}

<div class="container body-content">

    <div>

    </div>

</div>

@section scripts {
    <script>
        var mode = "@ViewBag.Mode";
        function getQuizQuestions(mode) {
            var url = "/Quiz/GetQuizQuestions?tagName=@ViewBag.mode";
                $.get(url, function (data) {
                    //dropDownData = data.map(function (item) {
                    //    var newObject = { name: item.TagName, id: item.TagId }
                    //    return newObject;
                    //    console.log(data);
                    //});
                    console.log(data);
                    //$('.dropdown-mul-1').data('dropdown').update(dropDownData, true);
                });
            }
            @if (@ViewBag.tags != null)
            {
                <Text>
                $('#target').val(ViewBag.tags.toString());
                </Text>
            }
        getQuizQuestions();
    </script>
}

CustomAuthenticationMVC/CustomAuthenticationMVC/Views/Quiz/GetAllQuestions.cshtml
@model PagedList.IPagedList<CustomAuthenticationMVC.DataAccess.Question>
@using PagedList;
@using PagedList.Mvc;
@section styles {
<style>
    tr:hover {
        background-color: #cfd7e6;
    }
    table {
        font-weight:100;
        margin-bottom:40px!important;
    }
    td {
        padding:0px!important;
    }
    .pagination>li {
        margin-left:20px;
    }
</style>
}
@{TempData.Keep();}
<div class="main-content-container container-fluid px-4">
    <!-- Page Header -->
    <!-- End Page Header -->


    @using (Html.BeginForm("GetAllQuestions", "Quiz", FormMethod.Get, new { @style = "margin-top:15px" }))
    {
        <div class="form-row">
            <div class="form-group col-md-3">
                @Html.TextBox("SearchString", TempData["CurrentFilter"] as string, new { @class = "form-control", @placeholder = "Tag / Text" })
            </div>
            <div class="form-group col-md-3">
                @Html.TextBox("userString", TempData["UserFilter"] as string, new { @class = "form-control", @placeholder = "Username" })
            </div>
            @*<div class="form-group col-md-2">
                    @Html.TextBox("completedString", TempData["CompletedFilter as string, new { @class = "form-control", @placeholder = "Ready" })
                </div>*@
            <div class="form-group col-md-2">
                <div class="custom-control custom-toggle custom-toggle-sm mb-1" style="margin-top:5px;">
                    <input type="checkbox" id="customToggle2" name="completedString" class="custom-control-input" @if (@TempData["CompletedFilter"] != null) { <text> checked</text> }>
                    <label class="custom-control-label" for="customToggle2">Verified</label>
                </div>
            </div>
            <div class="form-group col-md-2">
                <input type="submit" class="mb-2 btn btn-primary mr-1" value="Search" />
            </div>
            @*<div class="form-group col-md-3">
                    @Html.TextBox("SearchString", TempData["CurrentFilter as string, new { @class = "form-control", @placeholder = "Tag / Text" })
                </div>*@

        </div>
    }

    <table class="table" style="table-layout:fixed;">
        <tr>
            <th style="width:13%;">
                @Html.ActionLink("Tags", "GetAllQuestions", new { sortParam = "tags", currentFilter = TempData["CurrentFilter"], userFilter = TempData["UserFilter"], completedFilter = TempData["CompletedFilter"] })
            </th>
            <th style="width:90%;">
                @Html.ActionLink("Question", "GetAllQuestions", new { sortParam = "question", currentFilter = TempData["CurrentFilter"], userFilter = TempData["UserFilter"], completedFilter = TempData["CompletedFilter"] })
            </th>
            <th style="width:7%;">Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class='clickable-row' data-href='/Quiz/EditQuestion?questionId=@item.QuestionId' style="cursor:pointer;">
                <td style="white-space: nowrap; overflow: hidden; width:20%;">
                    @Html.DisplayFor(modelItem => item.QuestionTags)
                </td>
                <td style="white-space: nowrap; overflow: hidden; width:80%;">
                    @Html.DisplayFor(modelItem => item.QuestionText)
                </td>

                <td style="white-space: nowrap; overflow: hidden; width:20%;">
                    @Html.ActionLink("Delete", "DeleteQuestion", new { questionId = item.QuestionId })
                </td>
            </tr>
        }

    </table>
    @*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount*@
    <br />
    @*@Html.PagedListPager(Model, page => Url.Action("GetAllQuestions", new { page }))*@
    <div style="margin-left:40%">
        
            @Html.PagedListPager(Model, page => Url.Action("GetAllQuestions",
        new { page, sortParam = TempData["NameSortParm"], sortOrder = TempData["CurrentSort"], currentFilter = TempData["CurrentFilter"], userFilter = TempData["UserFilter"], completedFilter = TempData["CompletedFilter"] }))
        </div>
    
</div>


@section scripts {
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
}